### ISSUE TITLE
License for PyHSS code?

### ISSUE THREAD

**Issue by cchiaramelli** [nickvsnetworking/pyhss#143]
Hi there, Nick

I've been using PyHSS for testing purposes recently, and it have helped me a lot! Thanks for sharing it publicly on Github.
I noticed the current repository doesn't have any explicit License, so I would like to ask if it is possible to clarify this point. It would be nice to know it for contributing and usage purposes.

Thanks!

**Comment by laf0rge** [comment]
This i s actually a very serious problem! Without a license, nobody has the right to do anything with this code, not running it, not distributing it and not to modify it.

@nickvsnetworking please kindly clarify the license of PyHSS so potential users have legal clarity about what they can or can not do with this code.  Thanks!

Please also note that there are several references to a LICENSE file in parts of the code (that was apparently lifted from other projects/sources):

```
lib/lte.py:This source code is licensed under the BSD-style license found in the
lib/lte.py:LICENSE file in the root directory of this source tree. An additional grant
```
```
lib/milenage.py:This source code is licensed under the BSD-style license found in the
lib/milenage.py:LICENSE file in the root directory of this source tree. An additional grant
```

Note that removing the LICENSE file of that code may in itself be a license (and hence copyright) violation. Most BSD style licenses require that the license is always passed along with any copy of the code.

**Comment by laf0rge** [comment]
As there was no follow-up here, but @nickvsnetworking did make an update on this a week ago on an osmoocom mailing list, here's a link to the post: https://lists.osmocom.org/hyperkitty/list/openbsc@lists.osmocom.org/message/57XBEQG47HLEX7ZSS7UYZ6V4RCFGKJAZ/

**Comment by nickvsnetworking** [comment]
https://github.com/nickvsnetworking/pyhss/blob/master/LICENSE

Thanks all!
