### ISSUE TITLE
invalid TFT sent in Gx Re-Auth Request AVP: Flow-Description(507)

### ISSUE THREAD

**Issue by svinson1121** [nickvsnetworking/pyhss#188]
PyHSS 1.01
invalid TFT sent:

AVP: Flow-Description(507) l=74 f=VM- vnd=TGPP val=permit out 17 from /32 19680-19681 to 10.46.1.1/32 49120-49121

looks like PyHSS is not returning the value of {sdpDownlinkIpv4} 

[PYHSS-1.0.1-TFT-bug.pcap.zip](https://github.com/nickvsnetworking/pyhss/files/14030388/PYHSS-1.0.1-TFT-bug.pcap.zip)

also, the only log file created or updated in /var/log is pyhss_diameter.log

**Comment by davidkneipp** [comment]
Fixed in https://github.com/nickvsnetworking/pyhss/commit/a509e5c708a194faa8cc782af4296b60c17c35fa
