### ISSUE TITLE
Fix failed-to-decode sub-avp errors

### ISSUE THREAD

**Issue by nickvsnetworking** [nickvsnetworking/pyhss#19]
==> diameter.log <==
2021-03-17 07:20:41,066 : failed to decode sub-avp - error: invalid literal for int() with base 16: ''

Should only parse if length is greater than 0

**Comment by jiacnn** [comment]
i have same error ，you solved it？

**Comment by nickvsnetworking** [comment]
Hi @jiacnn ,
This has been resolved, please let me know if you're still seeing it after doing a Git pull,
Cheers,
Nick
