### ISSUE TITLE
when server send a DWR , client cant answer? 

### ISSUE THREAD

**Issue by jiacnn** [nickvsnetworking/pyhss#23]
when connected, server will send DWR to keep alive, but client cant answer a DWA, so the server stop the connect,how can i solved this problem?

**Comment by nickvsnetworking** [comment]
Hi @jiacnn ,
Can you please share a PCAP and a copy of the logs?
I assume you're running the Client software to tests, but it should be able to answer DWR with DWA,
Nick

**Comment by jiacnn** [comment]
@nickvsnetworking ,thanks 
I have solved it , i used Freediameter as the Server, and used this client to connect with Freediameter,  I modified the client so that it can receive DWR from the server at any time and answer DWA to server.

**Comment by nickvsnetworking** [comment]
Hi @jiacnn ,
Would you mind sharing the changes you made to the client so I can merge them in for everyone to use?
Nick

**Comment by nickvsnetworking** [comment]
Thanks @jiacnn , really apreciate it, have merged your changes,
Nick
